project:
  type: website
  output-dir: docs

website:
  back-to-top-navigation: true
  title: "Hahabula_blog"
  navbar:
    background: primary
    search: true
    logo: "./blog_icon.jpg"
    left:
      - text: 主页
        href: index.qmd
      - about.qmd
    right: 
      - icon: github
        href: https://github.com/

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    include-in-header:
      text: |
        <script>
        MathJax = {
          loader: {
            load: ['[tex]/boldsymbol']
          },
          tex: {
            tags: "none",
            inlineMath: [['$','$'], ['\\(','\\)']],
            displayMath: [['$$','$$'], ['\\[','\\]']],
            processEscapes: true,
            processEnvironments: true,
            packages: {
              '[+]': ['boldsymbol']
            }
          }
        };
        </script>
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
  pdf:
    include-in-header:
      text: |
        \usepackage{xeCJK}
    pdf-engine: xelatex
    keep-tex: true



filters:
  - pseudocode

pseudocode:
  caption-prefix: "算法"
  reference-prefix: "算法"
  caption-number: true
  html-line-number: true
  html-line-number-punc: " "
  html-no-end: false
  pdf-placement: "htb!"
  pdf-line-number: true



